#!/usr/bin/env bash

jj-resolve-cid() {
  [[ $# == 1 ]]
  jj --no-pager log --no-graph -T change_id -r "$1"
}

msg() {
  echo "$*" >&2
}

fail() {
  msg "$*"
  exit 1
}

# State after git amend
#
#  A‥‥A′
#  │ ╱
#  B
#
# Idea to fix:
#
# 1. Backout old A on top of A′ (-A)
#
#    -A
#   ⋰ │
#  A  A′
#  │ ╱
#  B
#
# 2. Squash -A into A′ which results in diff between A and A′ likely conflicting.
#
#  A  A*
#  │ ╱
#  B
#
# 3. Rebase that to A which resolves conflict
#
#  A*
#  │ ⋱
#  A  A*
#  │ ╱
#  B
#
# 4. Squash it into A
#
#  A′
#  │
#  B
#

sync-amend() {
  local old_hash new_hash rest
  local old_cid new_cid
  while read old_hash new_hash rest; do
    old_cid=$(jj-resolve-cid "$old_hash")  # A
    new_cid=$(jj-resolve-cid "$new_hash")  # A'
    [[ "$old_cid" == "$new_cid" ]] && continue  # looks like Jujutsu handled it transparently
    cat <<EOS
# $old_hash $new_hash $rest
jj backout -r $old_cid -d $new_cid
# Squashed -A into A' preserving original commit message. Now new A* have only
# commit message and no files. But all descendants of A' are preserved.
EDITOR="$script x-jj-editor-drop-backout $old_hash" \
  jj squash -r '$new_cid+ & description(regex:"back.* commit $old_hash")'
# Move A* tree on top of original A and squash it overwriting commit message
jj rebase -s $new_cid -d $old_cid
jj describe -r $old_cid -m '' # truncate old message in favor of new one
EDITOR="true" \
  jj squash -r $new_cid
EOS
  done | (set -eo pipefail; eval "$(cat)")
}

set -exo pipefail

readonly script=$(realpath "$0")

case "$1" in
amend) "sync-$1" ;;
x-jj-editor-drop-backout) sed -i -e "/^backout of commit $2$/d" "$3"; exit; ;;
*) fail "Unsupported event $1" ;;
esac

